<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>ur</string>
    <string>urs</string>
  </array>
  <key>name</key>
  <string>UrWeb</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>comment</key>
      <string>More UrWeb (to fix nesting in XML)</string>
      <key>begin</key>
      <string>{</string>
      <key>end</key>
      <string>}</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>comment</key>
      <string>UrWeb keywords</string>
      <key>match</key>
      <string>(\b(and|case|class|con|constraint|constraints|datatype|else|end|extern|fn|map|fun|functor|if|include|of|open|let|in|rec|sequence|ensure_index|sig|signature|cookie|style|task|policy|struct|structure|table|view|then|type|val|where)\b)</string>
      <key>name</key>
      <string>keyword.source.ur</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>UrWeb builtins</string>
      <key>match</key>
      <string>(\b(bool|list|True|False|Some|None|result|Success|Failure|task|unit|eq|num|ord|show|read|monad|transaction|source|signal|int|float|time|blob|string|char|money)\b|&lt;xml\/&gt;)</string>
      <key>name</key>
      <string>keyword.source.ur.builtins</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>UrWeb symbols</string>
      <key>match</key>
      <string>(\$|\@)</string>
      <key>name</key>
      <string>keyword.source.ur.symbols</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>SQL block: (SQL ...), (WHERE ...), (FROM ...), (SELECT1 ...), (SELECT ...), (INSERT INTO ...), (UPDATE ...), (DELETE FROM ...)</string>
      <key>begin</key>
      <string>\(\s*(SQL|WHERE|FROM|SELECT1|SELECT|INSERT\s+INTO|UPDATE|DELETE\s+FROM)\b</string>
      <key>end</key>
      <string>\)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.source.ur.sql</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>source.sql</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#urwebEscapeInject</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#urwebEscape</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#sqlParenGroup</string>
        </dict>
        <dict>
          <key>include</key>
          <string>source.sql</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>comment</key>
      <string>Numeric constants</string>
      <key>match</key>
      <string>\b[0-9]+\b</string>
      <key>name</key>
      <string>constant.numeric.ur</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>uppercase Ur/Web identifiers</string>
      <key>match</key>
      <string>\b[A-Z]([A-z0-9]*)\b</string>
      <key>name</key>
      <string>support.type.ur</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>String constant</string>
      <key>match</key>
      <string>"(\\"|[^"])*"</string>
      <key>name</key>
      <string>string.ur</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>Comment block</string>
      <key>begin</key>
      <string>\(\*</string>
      <key>end</key>
      <string>\*\)</string>
      <key>name</key>
      <string>comment.ur</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#nestedComment</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>comment</key>
      <string>XML Blocks - embeds HTML grammar with Ur/Web escapes {e} and {[e]}</string>
      <key>begin</key>
      <string>\&lt;xml\&gt;</string>
      <key>end</key>
      <string>\&lt;/xml\&gt;</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.tag.ur</string>
        </dict>
      </dict>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.tag.ur</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>text.html.basic</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>comment</key>
          <string>Ur/Web (* ... *) comments inside XML</string>
          <key>begin</key>
          <string>\(\*</string>
          <key>end</key>
          <string>\*\)</string>
          <key>name</key>
          <string>comment.block.ur</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#nestedComment</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>include</key>
          <string>#urwebEscapeInject</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#urwebEscape</string>
        </dict>
        <dict>
          <key>comment</key>
          <string>Ur/Web custom tags (dyn, active) - tag opening with attributes</string>
          <key>begin</key>
          <string>(&lt;)(dyn|active)\b</string>
          <key>end</key>
          <string>(/?&gt;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict><key>name</key><string>punctuation.definition.tag.begin.html</string></dict>
            <key>2</key>
            <dict><key>name</key><string>entity.name.tag.html</string></dict>
          </dict>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict><key>name</key><string>punctuation.definition.tag.end.html</string></dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#urwebEscapeInject</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#urwebEscape</string>
            </dict>
            <dict>
              <key>include</key>
              <string>text.html.basic#attribute</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>comment</key>
          <string>Ur/Web custom tags (dyn, active) - closing tag</string>
          <key>match</key>
          <string>(&lt;/)(dyn|active)(&gt;)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict><key>name</key><string>punctuation.definition.tag.begin.html</string></dict>
            <key>2</key>
            <dict><key>name</key><string>entity.name.tag.html</string></dict>
            <key>3</key>
            <dict><key>name</key><string>punctuation.definition.tag.end.html</string></dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>text.html.basic</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>comment</key>
      <string>Symbols</string>
      <key>match</key>
      <string>(\(\)|=&gt;|:|::|:::|\+\+|---|--|\~|\[\]|-&gt;|--&gt;|&lt;-|&gt;&gt;&gt;|&lt;&lt;&lt;|\|&gt;|&lt;\|)</string>
      <key>name</key>
      <string>constant.character.ur</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>nestedComment</key>
    <dict>
      <key>begin</key>
      <string>\(\*</string>
      <key>end</key>
      <string>\*\)</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#nestedComment</string>
        </dict>
      </array>
    </dict>
    <key>urwebEscapeInject</key>
    <dict>
      <key>comment</key>
      <string>{[ e ]} - inject an Ur expression via Top.txt</string>
      <key>begin</key>
      <string>\{\[</string>
      <key>end</key>
      <string>\]\}</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.embedded.ur</string>
        </dict>
      </dict>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.embedded.ur</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>source.ur</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
    <key>urwebEscape</key>
    <dict>
      <key>comment</key>
      <string>{ e } - computed Ur/Web expression inside XML or SQL</string>
      <key>begin</key>
      <string>\{(?!\[)</string>
      <key>end</key>
      <string>\}</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.embedded.ur</string>
        </dict>
      </dict>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.embedded.ur</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>source.ur</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
    <key>sqlParenGroup</key>
    <dict>
      <key>comment</key>
      <string>Balanced parens inside SQL so nested ( ) don't close the outer region early</string>
      <key>begin</key>
      <string>\(</string>
      <key>end</key>
      <string>\)</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#urwebEscapeInject</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#urwebEscape</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#sqlParenGroup</string>
        </dict>
        <dict>
          <key>include</key>
          <string>source.sql</string>
        </dict>
      </array>
    </dict>
  </dict>
  <key>scopeName</key>
  <string>source.ur</string>
  <key>uuid</key>
  <string>65be9466-98df-11e4-b8aa-123b93f75cba</string>
</dict>
</plist>
